Write-Host "----------------------------------------"
Write-Host "LocalAi - AUREX Migration Guide"
Write-Host "----------------------------------------"
Write-Host ""
Write-Host "AUREX currently spawns llama.cpp internally and manages its own model."
Write-Host "After migration, AUREX will use LocalAi's API instead."
Write-Host "This script will guide you through the changes."
Write-Host ""

try {
    Invoke-RestMethod -Uri "http://127.0.0.1:8080/health" -Method GET -ErrorAction Stop | Out-Null
} catch {
    Write-Host "Warning: LocalAi is not running. Start it with .\start.ps1 first."
    Write-Host ""
}

$aurexRoot = "C:\AUREX"
if (-not (Test-Path $aurexRoot)) {
    Write-Host "AUREX not found at C:\AUREX. Update this script if AUREX is elsewhere."
    Write-Host ""
}

Write-Host "----------------------------------------"
Write-Host "STEP 1: Install OpenAI SDK in AUREX's environment"
Write-Host ""
Write-Host "In AUREX's directory, run:"
Write-Host "  pip install openai"
Write-Host ""
Write-Host "Or add to AUREX's requirements.txt:"
Write-Host "  openai>=1.0.0"
Write-Host "----------------------------------------"
Write-Host ""

$helperContent = @'
"""
LocalAi client for AUREX.
Drop-in replacement for direct llama.cpp calls.
Generated by LocalAi migrate_aurex.ps1
"""

from openai import OpenAI

LOCALAI_BASE_URL = "http://127.0.0.1:8080/v1"
LOCALAI_API_KEY = "localai"


def get_client() -> OpenAI:
    """Return a configured OpenAI client pointing at LocalAi."""
    return OpenAI(
        base_url=LOCALAI_BASE_URL,
        api_key=LOCALAI_API_KEY,
    )


def chat(
    model: str,
    messages: list[dict],
    max_tokens: int = 2048,
    temperature: float = 0.7,
    stream: bool = False,
):
    """
    Send a chat completion request to LocalAi.

    Drop-in for AUREX's existing inference calls.
    """
    client = get_client()
    return client.chat.completions.create(
        model=model,
        messages=messages,
        max_tokens=max_tokens,
        temperature=temperature,
        stream=stream,
    )
'@

if (Test-Path $aurexRoot) {
    $helperPath = Join-Path $aurexRoot "localai_client.py"
    $helperContent | Set-Content -Path $helperPath -Encoding utf8
}

Write-Host "----------------------------------------"
Write-Host "STEP 2: Replace AUREX inference calls"
Write-Host ""
Write-Host "A helper file has been created at:"
Write-Host "  C:\AUREX\localai_client.py"
Write-Host ""
Write-Host "In AUREX, replace direct llama.cpp calls with:"
Write-Host ""
Write-Host "  from localai_client import chat"
Write-Host ""
Write-Host "  response = chat("
Write-Host "      model='qwen3.5-4b-q4_k_m',"
Write-Host "      messages=[{'role': 'user', 'content': your_prompt}],"
Write-Host "      max_tokens=2048,"
Write-Host "  )"
Write-Host "  answer = response.choices[0].message.content"
Write-Host "----------------------------------------"
Write-Host ""

Write-Host "----------------------------------------"
Write-Host "STEP 3: Verify the connection"
Write-Host ""
Write-Host "Run this test from C:\LocalAi:"
Write-Host "  .\venv\Scripts\python.exe scripts\test_aurex_connection.py"
Write-Host ""
Write-Host "Expected output:"
Write-Host "  All tests passed. LocalAi is OpenAI SDK compatible."
Write-Host "----------------------------------------"
Write-Host ""

Write-Host "----------------------------------------"
Write-Host "Migration guide complete."
Write-Host ""
Write-Host "Make sure LocalAi is running before starting AUREX:"
Write-Host "  .\start.ps1"
Write-Host ""
Write-Host "Load your preferred model before AUREX makes requests:"
Write-Host "  curl -X POST http://localhost:8080/localai/models/load"
Write-Host "    -H 'Content-Type: application/json'"
Write-Host "    -d '{\"model_id\": \"qwen3.5-4b-q4_k_m\"}'"
Write-Host "----------------------------------------"
